### ISSUE TITLE
Changes to naming convention Conan-Center

### ISSUE THREAD

**Issue by prince-chrismc** [Stiffstream/restinio-conan#10]
In recent developments, the conan center community has been changing the name convention for packages. These changes are being following by the bincrafters community.

An example is boost...
```sh
$ conan search -r conan-center boost
Existing package recipes:

boost/1.64.0@conan/stable
boost/1.65.1@conan/stable
boost/1.66.0@conan/stable
boost/1.67.0@conan/stable
boost/1.68.0@conan/stable
boost/1.69.0@conan/stable
boost/1.70.0
boost/1.70.0@conan/stable
boost/1.71.0
boost/1.71.0@conan/stable
```

They are no longer mentioning `@user/channel`.

Worse is that everything is no lower case... deps like `OpenSSL` became `openssl` which breaks the case sensitivity of conan.

Needless moving forward for future release the deps might need more complicate changes then just the version

Currently the OpenSSL is in conflict with some other packages that are now using openssl from bincrafters.

**Comment by Croydon** [comment]
Some clarifications:

Conan has started the new [Conan Center Index](https://github.com/conan-io/conan-center-index). It will soon be the only way to include packages in the official Conan Center. 

Bincrafters always worked towards including packages into the Conan Center. So when packages are ready for the Conan Center Index (CCI), we migrate them there and stop maintaining the Bincrafters' version.

Bincrafters' packages still have the `@bincrafters/stable` part. All packages within the CCI don't have the `@user/channel` part. 

What was a true naming convention change is that names are lower-case, but this was actually adopted a long time ago. Just recipes which existed pre-adoption weren't immediately renamed because of breakages on case-insensitive operating systems like Windows. On case-sensitives systems like Linux `OpenSSL/1.1.1d` and `openssl/1.1.1d@conan/stable` can co-exist.
